# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-cloud
env: 
  BUCKET_NAME : " flasck-app-packages"
  APP_NAME :  "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask_app_${{ github.sha }}.zip 

on:
  push:
    branches:
      - master
#  pull_request:
#    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
  # This workflow contains a single job called "build"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: GIT clone our repo
      uses: actions/checkout@v1
      


    - name: create zip deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
